### ISSUE TITLE
Paraglider lets you glide upward forever

### ISSUE THREAD

**Issue by Cephelo** [Kamtheman56/Zelda_Mod#14] opened 2024-08-27 21:44 UTC
When you hold spacebar while using the paraglider, you can just... go up for as long as you want.  In this state, the paraglider essentially just lets you fly slower.  Not sure what's causing this, or if it's intended?

Side note, why does the releaseUsing method in HeroBowItem being Overridden?  It's the exact same as the one vanilla Minecraft's BowItem.

**Comment by Kamtheman56** [comment] 2024-08-29 13:55
Thank you for reporting this bug! That's not intended behavior and will be fixed in the upcoming release. The paraglider in general is a WIP item that is only available in the creative tab, so it must've slipped through the cracks when I was working on it.

In terms of the HeroBow, I simply wrote it a long time ago and never went back to clean it up! This redundant code will be fixed as well.

**Closed by Kamtheman56** 2024-08-29 13:55 UTC

**Comment by Kamtheman56** [comment] 2024-09-02 02:00
Correction, I hadn't actually looked back at the code for the HeroBow. The releaseUsing method is overridden to allow complete accuracy whilst wearing the Hawkeye item.

**Comment by Cephelo** [comment] 2024-09-20 22:37
I know I should just make a new issue, but I figure they could be related - when using the paraglider while flying with the elytra, you speed up SIGNIFICANTLY.  At least hundreds of blocks per second O_O

**Comment by Kamtheman56** [comment] 2024-09-23 17:34
Thanks for your bug reporting! This has been fixed for version 1.2 and you are now unable to paraglide whilst using an Eltyra Item.

**Comment by Cephelo** [comment] 2024-09-23 18:53
Thank you so much!  Can't wait to play with the new content :)
